{% set name = "python-novaclient" %}
{% set version = "17.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cda999e2254787b962e14859f6ca71de640963f3b35c1685fb51ce3a7a0a8958

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nova = novaclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python >=3.6
    - setuptools
  run:
    - pbr
    - keystoneauth1
    - iso8601
    - oslo.i18n
    - oslo.serialization
    - oslo.utils
    - prettytable <0.8,>=0.7.2
    - python >=3.6
    - setuptools
    - simplejson

test:
  imports:
    - novaclient

about:
  home: https://docs.openstack.org/python-novaclient/latest
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Client library for OpenStack Compute API
  doc_url: https://docs.openstack.org/python-novaclient/latest
  dev_url: https://opendev.org/openstack/python-novaclient

extra:
  recipe-maintainers:
    - tschoonj
