{% set name = "python-novaclient" %}
{% set version = "17.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a0ab422f217eeb9043ba786ecb3925c8b66baa142195ed211db37c78eff3c5f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nova = novaclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python >=3.6
    - setuptools
  run:
    - babel
    - iso8601
    - keystoneauth1
    - oslo.i18n
    - oslo.serialization
    - oslo.utils
    - pbr
    - prettytable <0.8,>=0.7.2
    - python >=3.6
    - setuptools
    - simplejson

test:
  imports:
    - novaclient

about:
  home: https://docs.openstack.org/python-novaclient/latest
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Client library for OpenStack Compute API
  doc_url: https://docs.openstack.org/python-novaclient/latest
  dev_url: https://opendev.org/openstack/python-novaclient

extra:
  recipe-maintainers:
    - tschoonj
